[2025-01-08T12:11:50.046+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag_insert_log.trancate_data_ft_posting_data scheduled__2025-01-07T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
