[2025-01-06T23:43:04.705+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_insert_log.sql_ft_balance manual__2025-01-06T23:42:13.208216+00:00 [queued]>
[2025-01-06T23:43:04.782+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_insert_log.sql_ft_balance manual__2025-01-06T23:42:13.208216+00:00 [queued]>
[2025-01-06T23:43:04.790+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-01-06T23:43:04.858+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): sql_ft_balance> on 2025-01-06 23:42:13.208216+00:00
[2025-01-06T23:43:04.953+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_insert_log', 'sql_ft_balance', 'manual__2025-01-06T23:42:13.208216+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dag_insert_log.py', '--cfg-path', '/tmp/tmpp563tib3']
[2025-01-06T23:43:04.925+0000] {standard_task_runner.py:60} INFO - Started process 692 to run task
[2025-01-06T23:43:04.967+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask sql_ft_balance
[2025-01-06T23:43:05.485+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_insert_log.sql_ft_balance manual__2025-01-06T23:42:13.208216+00:00 [running]> on host 22295d32c47d
[2025-01-06T23:43:06.365+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='saida' AIRFLOW_CTX_DAG_ID='dag_insert_log' AIRFLOW_CTX_TASK_ID='sql_ft_balance' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T23:42:13.208216+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-06T23:42:13.208216+00:00'
[2025-01-06T23:43:06.376+0000] {sql.py:276} INFO - Executing: CALL ds.stage_to_ds_ft_balance_f();
[2025-01-06T23:43:06.434+0000] {base.py:83} INFO - Using connection ID '***-db' for task execution.
[2025-01-06T23:43:06.499+0000] {base.py:83} INFO - Using connection ID '***-db' for task execution.
[2025-01-06T23:43:06.906+0000] {sql.py:450} INFO - Running statement: CALL ds.stage_to_ds_ft_balance_f();, parameters: None
[2025-01-06T23:43:07.120+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_insert_log, task_id=sql_ft_balance, execution_date=20250106T234213, start_date=20250106T234304, end_date=20250106T234307
[2025-01-06T23:43:07.315+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-06T23:43:07.551+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
