[2025-01-08T12:28:11.590+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: currency_dag.ft_balance_f manual__2025-01-08T12:28:09.350757+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
